GET http://localhost:3000/messages
Accept: application/json
Accept-Encoding: gzip
#Authorization: Basic YnVja3k6c2llcnJh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJ1Y2t5Iiwicm9sZXMiOlsidXNlciJdLCJpYXQiOjE2MzAwNTY0ODEsImV4cCI6MTYzMDA2MDA4MX0.2ySnp-q6WSlkSZrBHJook50t0XOI3fV_gpqwwcZZ6H0
Content-Type: application/json

###

GET http://localhost:3000/messages/1
Accept: application/json
Content-Type: application/json

###

POST http://localhost:3000/messages
Accept: application/json
Content-Type: application/json

{
  "from": "1",
  "to": "2",
  "subject": "Hi!",
  "body": "My name is...."
}

###

PATCH http://localhost:3000/messages/1
Accept: application/json
Content-Type: application/json

{
  "subject": "Hello!"
}

###

DELETE http://localhost:3000/messages/1
Accept: application/json
Content-Type: application/json

###

GET http://localhost:3000/messages/from/1/to/2
Accept: application/json
Content-Type: application/json

###

GET http://localhost:3000/users
Accept: application/json
Content-Type: application/json

###

GET http://localhost:3000/test
Accept: application/json
Content-Type: application/json

###

POST http://localhost:3000/messages
Content-Type: multipart/form-data; boundary=WebAppBoundry
Accept: application/json

--WebAppBoundry
Content-Disposition: form-data; name="attachments"; filename="cover.jpg"
Content-Type: image/jpeg

<./cover.jpg
--WebAppBoundry

###

POST http://localhost:3000/security
Accept: application/json
Content-Type: application/json

{
  "username": "bucky",
  "password": "sierra"
}

###

POST http://localhost:3000/security
Accept: application/json
Content-Type: application/json

{
  "username": "bucky",
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJ1Y2t5IiwiaWF0IjoxNjMwMDU0NzMyLCJleHAiOjE2MzAwNTQ3NDJ9.v-vaoIqlCkSfr9uXS0CXlvpsUYohJBZG40PX-3TvRpI"
}