GET http://localhost:3000/messages
Accept: application/json
Accept-Encoding: gzip
Content-Type: application/json

###

GET http://localhost:3000/messages/1
Accept: application/json
Content-Type: application/json

###

POST http://localhost:3000/messages
Accept: application/json
Content-Type: application/json

{
  "from": "1",
  "to": "2",
  "subject": "Hi!",
  "body": "My name is...."
}

###

PATCH http://localhost:3000/messages/1
Accept: application/json
Content-Type: application/json

{
  "subject": "Hello!"
}

###

DELETE http://localhost:3000/messages/1
Accept: application/json
Content-Type: application/json

###

GET http://localhost:3000/messages/from/1/to/2
Accept: application/json
Content-Type: application/json

###

GET http://localhost:3000/users
Accept: application/json
Content-Type: application/json

###

GET http://localhost:3000/test
Accept: application/json
Content-Type: application/json

###

POST http://localhost:3000/messages
Content-Type: multipart/form-data; boundary=WebAppBoundry
Accept: application/json

--WebAppBoundry
Content-Disposition: form-data; name="attachments"; filename="cover.jpg"
Content-Type: image/jpeg

<./cover.jpg
--WebAppBoundry