GET http://localhost:3000/messages
Accept: application/json
Content-Type: application/json

###

GET http://localhost:3000/messages/1
Accept: application/json
Content-Type: application/json

###

GET http://localhost:3000/messages/from/1/to/2
Accept: application/json
Content-Type: application/json

###

GET http://localhost:3000/users
Accept: application/json
Content-Type: application/json

###

GET http://localhost:3000/test
Accept: application/json
Content-Type: application/json

###