version: '3'
services:
  app:
    image: landrzejewski/app
    environment:
      TOKEN_SIGNATURE: "symmetrickey"
    ports:
      - "3000:8080"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: app
      MONGO_USERNAME: admin
      MONGO_PASSWORD: admin
    volumes:
      - ./data/mongo:/data/db
      - ./mongo-entrypoint.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro